/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.5 at Mon May 11 20:25:44 2020. */

#include "blockchain.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Block_fields[4] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, Block, hash, hash, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, Block, header, hash, &BlockHeader_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, Block, body, header, &BlockBody_fields),
    PB_LAST_FIELD
};

const pb_field_t BlockHeader_fields[13] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, BlockHeader, chainID, chainID, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, BlockHeader, prevBlockHash, chainID, 0),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, BlockHeader, blockNo, prevBlockHash, 0),
    PB_FIELD(  4, INT64   , SINGULAR, STATIC  , OTHER, BlockHeader, timestamp, blockNo, 0),
    PB_FIELD(  5, BYTES   , SINGULAR, CALLBACK, OTHER, BlockHeader, blocksRootHash, timestamp, 0),
    PB_FIELD(  6, BYTES   , SINGULAR, CALLBACK, OTHER, BlockHeader, txsRootHash, blocksRootHash, 0),
    PB_FIELD(  7, BYTES   , SINGULAR, CALLBACK, OTHER, BlockHeader, receiptsRootHash, txsRootHash, 0),
    PB_FIELD(  8, UINT64  , SINGULAR, STATIC  , OTHER, BlockHeader, confirms, receiptsRootHash, 0),
    PB_FIELD(  9, BYTES   , SINGULAR, CALLBACK, OTHER, BlockHeader, pubKey, confirms, 0),
    PB_FIELD( 10, BYTES   , SINGULAR, CALLBACK, OTHER, BlockHeader, coinbaseAccount, pubKey, 0),
    PB_FIELD( 11, BYTES   , SINGULAR, CALLBACK, OTHER, BlockHeader, sign, coinbaseAccount, 0),
    PB_FIELD( 12, BYTES   , SINGULAR, CALLBACK, OTHER, BlockHeader, consensus, sign, 0),
    PB_LAST_FIELD
};

const pb_field_t BlockBody_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, BlockBody, txs, txs, &Tx_fields),
    PB_LAST_FIELD
};

const pb_field_t TxList_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, TxList, txs, txs, &Tx_fields),
    PB_LAST_FIELD
};

const pb_field_t Tx_fields[3] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, Tx, hash, hash, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, Tx, body, hash, &TxBody_fields),
    PB_LAST_FIELD
};

const pb_field_t TxBody_fields[11] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, TxBody, nonce, nonce, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, TxBody, account, nonce, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, TxBody, recipient, account, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, TxBody, amount, recipient, 0),
    PB_FIELD(  5, BYTES   , SINGULAR, CALLBACK, OTHER, TxBody, payload, amount, 0),
    PB_FIELD(  6, UINT64  , SINGULAR, STATIC  , OTHER, TxBody, gasLimit, payload, 0),
    PB_FIELD(  7, BYTES   , SINGULAR, CALLBACK, OTHER, TxBody, gasPrice, gasLimit, 0),
    PB_FIELD(  8, UENUM   , SINGULAR, STATIC  , OTHER, TxBody, type, gasPrice, 0),
    PB_FIELD(  9, BYTES   , SINGULAR, CALLBACK, OTHER, TxBody, chainIdHash, type, 0),
    PB_FIELD( 10, BYTES   , SINGULAR, CALLBACK, OTHER, TxBody, sign, chainIdHash, 0),
    PB_LAST_FIELD
};

const pb_field_t TxIdx_fields[3] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, TxIdx, blockHash, blockHash, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, TxIdx, idx, blockHash, 0),
    PB_LAST_FIELD
};

const pb_field_t TxInBlock_fields[3] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, TxInBlock, txIdx, txIdx, &TxIdx_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, TxInBlock, tx, txIdx, &Tx_fields),
    PB_LAST_FIELD
};

const pb_field_t State_fields[6] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, State, nonce, nonce, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, State, balance, nonce, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, State, codeHash, balance, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, State, storageRoot, codeHash, 0),
    PB_FIELD(  5, UINT64  , SINGULAR, STATIC  , OTHER, State, sqlRecoveryPoint, storageRoot, 0),
    PB_LAST_FIELD
};

const pb_field_t AccountProof_fields[9] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, AccountProof, state, state, &State_fields),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, AccountProof, inclusion, state, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, AccountProof, key, inclusion, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, AccountProof, proofKey, key, 0),
    PB_FIELD(  5, BYTES   , SINGULAR, CALLBACK, OTHER, AccountProof, proofVal, proofKey, 0),
    PB_FIELD(  6, BYTES   , SINGULAR, CALLBACK, OTHER, AccountProof, bitmap, proofVal, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, AccountProof, height, bitmap, 0),
    PB_FIELD(  8, BYTES   , REPEATED, CALLBACK, OTHER, AccountProof, auditPath, height, 0),
    PB_LAST_FIELD
};

const pb_field_t ContractVarProof_fields[9] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, ContractVarProof, value, value, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, ContractVarProof, inclusion, value, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, ContractVarProof, proofKey, inclusion, 0),
    PB_FIELD(  5, BYTES   , SINGULAR, CALLBACK, OTHER, ContractVarProof, proofVal, proofKey, 0),
    PB_FIELD(  6, BYTES   , SINGULAR, CALLBACK, OTHER, ContractVarProof, bitmap, proofVal, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, ContractVarProof, height, bitmap, 0),
    PB_FIELD(  8, BYTES   , REPEATED, CALLBACK, OTHER, ContractVarProof, auditPath, height, 0),
    PB_FIELD(  9, BYTES   , SINGULAR, CALLBACK, OTHER, ContractVarProof, key, auditPath, 0),
    PB_LAST_FIELD
};

const pb_field_t StateQueryProof_fields[3] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, StateQueryProof, contractProof, contractProof, &AccountProof_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, StateQueryProof, varProofs, contractProof, &ContractVarProof_fields),
    PB_LAST_FIELD
};

const pb_field_t Receipt_fields[16] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, Receipt, contractAddress, contractAddress, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, Receipt, status, contractAddress, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, Receipt, ret, status, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, Receipt, txHash, ret, 0),
    PB_FIELD(  5, BYTES   , SINGULAR, CALLBACK, OTHER, Receipt, feeUsed, txHash, 0),
    PB_FIELD(  6, BYTES   , SINGULAR, CALLBACK, OTHER, Receipt, cumulativeFeeUsed, feeUsed, 0),
    PB_FIELD(  7, BYTES   , SINGULAR, CALLBACK, OTHER, Receipt, bloom, cumulativeFeeUsed, 0),
    PB_FIELD(  8, MESSAGE , REPEATED, CALLBACK, OTHER, Receipt, events, bloom, &Event_fields),
    PB_FIELD(  9, UINT64  , SINGULAR, STATIC  , OTHER, Receipt, blockNo, events, 0),
    PB_FIELD( 10, BYTES   , SINGULAR, CALLBACK, OTHER, Receipt, blockHash, blockNo, 0),
    PB_FIELD( 11, INT32   , SINGULAR, STATIC  , OTHER, Receipt, txIndex, blockHash, 0),
    PB_FIELD( 12, BYTES   , SINGULAR, CALLBACK, OTHER, Receipt, from, txIndex, 0),
    PB_FIELD( 13, BYTES   , SINGULAR, CALLBACK, OTHER, Receipt, to, from, 0),
    PB_FIELD( 14, BOOL    , SINGULAR, STATIC  , OTHER, Receipt, feeDelegation, to, 0),
    PB_FIELD( 15, UINT64  , SINGULAR, STATIC  , OTHER, Receipt, gasUsed, feeDelegation, 0),
    PB_LAST_FIELD
};

const pb_field_t Event_fields[9] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, Event, contractAddress, contractAddress, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, Event, eventName, contractAddress, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, Event, jsonArgs, eventName, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, Event, eventIdx, jsonArgs, 0),
    PB_FIELD(  5, BYTES   , SINGULAR, CALLBACK, OTHER, Event, txHash, eventIdx, 0),
    PB_FIELD(  6, BYTES   , SINGULAR, CALLBACK, OTHER, Event, blockHash, txHash, 0),
    PB_FIELD(  7, UINT64  , SINGULAR, STATIC  , OTHER, Event, blockNo, blockHash, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, Event, txIndex, blockNo, 0),
    PB_LAST_FIELD
};

const pb_field_t FnArgument_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, FnArgument, name, name, 0),
    PB_LAST_FIELD
};

const pb_field_t Function_fields[6] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, Function, name, name, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, Function, arguments, name, &FnArgument_fields),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, Function, payable, arguments, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, Function, view, payable, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, Function, fee_delegation, view, 0),
    PB_LAST_FIELD
};

const pb_field_t StateVar_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, StateVar, name, name, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, StateVar, type, name, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, StateVar, len, type, 0),
    PB_LAST_FIELD
};

const pb_field_t ABI_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, ABI, version, version, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, ABI, language, version, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, ABI, functions, language, &Function_fields),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, ABI, state_variables, functions, &StateVar_fields),
    PB_LAST_FIELD
};

const pb_field_t Query_fields[3] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, Query, contractAddress, contractAddress, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, Query, queryinfo, contractAddress, 0),
    PB_LAST_FIELD
};

const pb_field_t StateQuery_fields[5] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, StateQuery, contractAddress, contractAddress, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, StateQuery, root, contractAddress, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, StateQuery, compressed, root, 0),
    PB_FIELD(  5, BYTES   , REPEATED, CALLBACK, OTHER, StateQuery, storageKeys, compressed, 0),
    PB_LAST_FIELD
};

const pb_field_t FilterInfo_fields[8] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, FilterInfo, contractAddress, contractAddress, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, FilterInfo, eventName, contractAddress, 0),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, FilterInfo, blockfrom, eventName, 0),
    PB_FIELD(  4, UINT64  , SINGULAR, STATIC  , OTHER, FilterInfo, blockto, blockfrom, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, FilterInfo, desc, blockto, 0),
    PB_FIELD(  6, BYTES   , SINGULAR, CALLBACK, OTHER, FilterInfo, argFilter, desc, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, FilterInfo, recentBlockCnt, argFilter, 0),
    PB_LAST_FIELD
};

const pb_field_t Proposal_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, Proposal, id, id, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, Proposal, description, id, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, Proposal, multipleChoice, description, 0),
    PB_LAST_FIELD
};

const pb_field_t Account_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, Account, address, address, 0),
    PB_LAST_FIELD
};

const pb_field_t AccountList_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, AccountList, accounts, accounts, &Account_fields),
    PB_LAST_FIELD
};

const pb_field_t BlockchainStatus_fields[6] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, BlockchainStatus, best_block_hash, best_block_hash, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, BlockchainStatus, best_height, best_block_hash, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, BlockchainStatus, consensus_info, best_height, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, BlockchainStatus, best_chain_id_hash, consensus_info, 0),
    PB_FIELD(  5, MESSAGE , SINGULAR, STATIC  , OTHER, BlockchainStatus, chain_info, best_chain_id_hash, &ChainInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t ChainId_fields[6] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, ChainId, magic, magic, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, ChainId, is_public, magic, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, ChainId, mainnet, is_public, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, ChainId, consensus, mainnet, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, ChainId, version, consensus, 0),
    PB_LAST_FIELD
};

const pb_field_t ChainInfo_fields[11] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, ChainInfo, id, id, &ChainId_fields),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, ChainInfo, bpNumber, id, 0),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, ChainInfo, maxblocksize, bpNumber, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, ChainInfo, maxtokens, maxblocksize, 0),
    PB_FIELD(  5, BYTES   , SINGULAR, CALLBACK, OTHER, ChainInfo, stakingminimum, maxtokens, 0),
    PB_FIELD(  6, BYTES   , SINGULAR, CALLBACK, OTHER, ChainInfo, totalstaking, stakingminimum, 0),
    PB_FIELD(  7, BYTES   , SINGULAR, CALLBACK, OTHER, ChainInfo, gasprice, totalstaking, 0),
    PB_FIELD(  8, BYTES   , SINGULAR, CALLBACK, OTHER, ChainInfo, nameprice, gasprice, 0),
    PB_FIELD(  9, BYTES   , SINGULAR, CALLBACK, OTHER, ChainInfo, totalvotingpower, nameprice, 0),
    PB_FIELD( 10, BYTES   , SINGULAR, CALLBACK, OTHER, ChainInfo, votingreward, totalvotingpower, 0),
    PB_LAST_FIELD
};

const pb_field_t ChainStats_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, ChainStats, report, report, 0),
    PB_LAST_FIELD
};

const pb_field_t Input_fields[5] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, Input, hash, hash, 0),
    PB_FIELD(  2, BYTES   , REPEATED, CALLBACK, OTHER, Input, address, hash, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, Input, value, address, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, Input, script, value, 0),
    PB_LAST_FIELD
};

const pb_field_t Output_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Output, index, index, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, Output, address, index, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, Output, value, address, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, Output, script, value, 0),
    PB_LAST_FIELD
};

const pb_field_t Empty_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t SingleBytes_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, SingleBytes, value, value, 0),
    PB_LAST_FIELD
};

const pb_field_t SingleString_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, SingleString, value, value, 0),
    PB_LAST_FIELD
};

const pb_field_t AccountAddress_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, AccountAddress, value, value, 0),
    PB_LAST_FIELD
};

const pb_field_t AccountAndRoot_fields[4] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, AccountAndRoot, Account, Account, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, AccountAndRoot, Root, Account, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, AccountAndRoot, Compressed, Root, 0),
    PB_LAST_FIELD
};

const pb_field_t ListParams_fields[6] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, ListParams, hash, hash, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, ListParams, height, hash, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, ListParams, size, height, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, ListParams, offset, size, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, ListParams, asc, offset, 0),
    PB_LAST_FIELD
};

const pb_field_t PageParams_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, PageParams, offset, offset, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, PageParams, size, offset, 0),
    PB_LAST_FIELD
};

const pb_field_t BlockBodyPaged_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, BlockBodyPaged, total, total, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, BlockBodyPaged, offset, total, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, BlockBodyPaged, size, offset, 0),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, BlockBodyPaged, body, size, &BlockBody_fields),
    PB_LAST_FIELD
};

const pb_field_t BlockBodyParams_fields[3] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, BlockBodyParams, hashornumber, hashornumber, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, BlockBodyParams, paging, hashornumber, &PageParams_fields),
    PB_LAST_FIELD
};

const pb_field_t BlockHeaderList_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, BlockHeaderList, blocks, blocks, &Block_fields),
    PB_LAST_FIELD
};

const pb_field_t BlockMetadata_fields[5] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, BlockMetadata, hash, hash, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, BlockMetadata, header, hash, &BlockHeader_fields),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, BlockMetadata, txcount, header, 0),
    PB_FIELD(  4, INT64   , SINGULAR, STATIC  , OTHER, BlockMetadata, size, txcount, 0),
    PB_LAST_FIELD
};

const pb_field_t BlockMetadataList_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, BlockMetadataList, blocks, blocks, &BlockMetadata_fields),
    PB_LAST_FIELD
};

const pb_field_t CommitResult_fields[4] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, CommitResult, hash, hash, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, CommitResult, error, hash, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, CommitResult, detail, error, 0),
    PB_LAST_FIELD
};

const pb_field_t CommitResultList_fields[2] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, CommitResultList, results, results, &CommitResult_fields),
    PB_LAST_FIELD
};

const pb_field_t VerifyResult_fields[3] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, VerifyResult, tx, tx, &Tx_fields),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, VerifyResult, error, tx, 0),
    PB_LAST_FIELD
};

const pb_field_t Personal_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, Personal, passphrase, passphrase, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, Personal, account, passphrase, &Account_fields),
    PB_LAST_FIELD
};

const pb_field_t ImportFormat_fields[5] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, ImportFormat, wif, wif, &SingleBytes_fields),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, ImportFormat, oldpass, wif, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, ImportFormat, newpass, oldpass, 0),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, ImportFormat, keystore, newpass, &SingleBytes_fields),
    PB_LAST_FIELD
};

const pb_field_t Staking_fields[3] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, Staking, amount, amount, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, Staking, when, amount, 0),
    PB_LAST_FIELD
};

const pb_field_t Vote_fields[3] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, Vote, candidate, candidate, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, Vote, amount, candidate, 0),
    PB_LAST_FIELD
};

const pb_field_t VoteParams_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, VoteParams, id, id, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, VoteParams, count, id, 0),
    PB_LAST_FIELD
};

const pb_field_t AccountVoteInfo_fields[3] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, AccountVoteInfo, staking, staking, &Staking_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, AccountVoteInfo, voting, staking, &VoteInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t VoteInfo_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, VoteInfo, id, id, 0),
    PB_FIELD(  2, STRING  , REPEATED, CALLBACK, OTHER, VoteInfo, candidates, id, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, VoteInfo, amount, candidates, 0),
    PB_LAST_FIELD
};

const pb_field_t VoteList_fields[3] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, VoteList, votes, votes, &Vote_fields),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, VoteList, id, votes, 0),
    PB_LAST_FIELD
};

const pb_field_t NodeReq_fields[3] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, NodeReq, timeout, timeout, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, NodeReq, component, timeout, 0),
    PB_LAST_FIELD
};

const pb_field_t Name_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, Name, name, name, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, Name, blockNo, name, 0),
    PB_LAST_FIELD
};

const pb_field_t NameInfo_fields[4] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, NameInfo, name, name, &Name_fields),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, NameInfo, owner, name, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, NameInfo, destination, owner, 0),
    PB_LAST_FIELD
};

const pb_field_t PeersParams_fields[3] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, PeersParams, noHidden, noHidden, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, PeersParams, showSelf, noHidden, 0),
    PB_LAST_FIELD
};

const pb_field_t KeyParams_fields[2] = {
    PB_FIELD(  1, STRING  , REPEATED, CALLBACK, FIRST, KeyParams, key, key, 0),
    PB_LAST_FIELD
};

const pb_field_t ServerInfo_fields[3] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, ServerInfo, status, status, &ServerInfo_StatusEntry_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, ServerInfo, config, status, &ServerInfo_ConfigEntry_fields),
    PB_LAST_FIELD
};

const pb_field_t ServerInfo_StatusEntry_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, ServerInfo_StatusEntry, key, key, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, ServerInfo_StatusEntry, value, key, 0),
    PB_LAST_FIELD
};

const pb_field_t ServerInfo_ConfigEntry_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, ServerInfo_ConfigEntry, key, key, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, ServerInfo_ConfigEntry, value, key, &ConfigItem_fields),
    PB_LAST_FIELD
};

const pb_field_t ConfigItem_fields[2] = {
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, FIRST, ConfigItem, props, props, &ConfigItem_PropsEntry_fields),
    PB_LAST_FIELD
};

const pb_field_t ConfigItem_PropsEntry_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, ConfigItem_PropsEntry, key, key, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, ConfigItem_PropsEntry, value, key, 0),
    PB_LAST_FIELD
};

const pb_field_t EventList_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, EventList, events, events, &Event_fields),
    PB_LAST_FIELD
};

const pb_field_t ConsensusInfo_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, ConsensusInfo, type, type, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, ConsensusInfo, info, type, 0),
    PB_FIELD(  3, STRING  , REPEATED, CALLBACK, OTHER, ConsensusInfo, bps, info, 0),
    PB_LAST_FIELD
};

const pb_field_t EnterpriseConfigKey_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, EnterpriseConfigKey, key, key, 0),
    PB_LAST_FIELD
};

const pb_field_t EnterpriseConfig_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, EnterpriseConfig, key, key, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, EnterpriseConfig, on, key, 0),
    PB_FIELD(  3, STRING  , REPEATED, CALLBACK, OTHER, EnterpriseConfig, values, on, 0),
    PB_LAST_FIELD
};





/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Block, header) < 65536 && pb_membersize(Block, body) < 65536 && pb_membersize(Tx, body) < 65536 && pb_membersize(TxInBlock, txIdx) < 65536 && pb_membersize(TxInBlock, tx) < 65536 && pb_membersize(AccountProof, state) < 65536 && pb_membersize(StateQueryProof, contractProof) < 65536 && pb_membersize(BlockchainStatus, chain_info) < 65536 && pb_membersize(ChainInfo, id) < 65536 && pb_membersize(BlockBodyPaged, body) < 65536 && pb_membersize(BlockBodyParams, paging) < 65536 && pb_membersize(BlockMetadata, header) < 65536 && pb_membersize(CommitResultList, results) < 65536 && pb_membersize(VerifyResult, tx) < 65536 && pb_membersize(Personal, account) < 65536 && pb_membersize(ImportFormat, wif) < 65536 && pb_membersize(ImportFormat, keystore) < 65536 && pb_membersize(AccountVoteInfo, staking) < 65536 && pb_membersize(NameInfo, name) < 65536 && pb_membersize(ServerInfo_ConfigEntry, value) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Block_BlockHeader_BlockBody_TxList_Tx_TxBody_TxIdx_TxInBlock_State_AccountProof_ContractVarProof_StateQueryProof_Receipt_Event_FnArgument_Function_StateVar_ABI_Query_StateQuery_FilterInfo_Proposal_Account_AccountList_BlockchainStatus_ChainId_ChainInfo_ChainStats_Input_Output_Empty_SingleBytes_SingleString_AccountAddress_AccountAndRoot_ListParams_PageParams_BlockBodyPaged_BlockBodyParams_BlockHeaderList_BlockMetadata_BlockMetadataList_CommitResult_CommitResultList_VerifyResult_Personal_ImportFormat_Staking_Vote_VoteParams_AccountVoteInfo_VoteInfo_VoteList_NodeReq_Name_NameInfo_PeersParams_KeyParams_ServerInfo_ServerInfo_StatusEntry_ServerInfo_ConfigEntry_ConfigItem_ConfigItem_PropsEntry_EventList_ConsensusInfo_EnterpriseConfigKey_EnterpriseConfig)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Block, header) < 256 && pb_membersize(Block, body) < 256 && pb_membersize(Tx, body) < 256 && pb_membersize(TxInBlock, txIdx) < 256 && pb_membersize(TxInBlock, tx) < 256 && pb_membersize(AccountProof, state) < 256 && pb_membersize(StateQueryProof, contractProof) < 256 && pb_membersize(BlockchainStatus, chain_info) < 256 && pb_membersize(ChainInfo, id) < 256 && pb_membersize(BlockBodyPaged, body) < 256 && pb_membersize(BlockBodyParams, paging) < 256 && pb_membersize(BlockMetadata, header) < 256 && pb_membersize(CommitResultList, results) < 256 && pb_membersize(VerifyResult, tx) < 256 && pb_membersize(Personal, account) < 256 && pb_membersize(ImportFormat, wif) < 256 && pb_membersize(ImportFormat, keystore) < 256 && pb_membersize(AccountVoteInfo, staking) < 256 && pb_membersize(NameInfo, name) < 256 && pb_membersize(ServerInfo_ConfigEntry, value) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Block_BlockHeader_BlockBody_TxList_Tx_TxBody_TxIdx_TxInBlock_State_AccountProof_ContractVarProof_StateQueryProof_Receipt_Event_FnArgument_Function_StateVar_ABI_Query_StateQuery_FilterInfo_Proposal_Account_AccountList_BlockchainStatus_ChainId_ChainInfo_ChainStats_Input_Output_Empty_SingleBytes_SingleString_AccountAddress_AccountAndRoot_ListParams_PageParams_BlockBodyPaged_BlockBodyParams_BlockHeaderList_BlockMetadata_BlockMetadataList_CommitResult_CommitResultList_VerifyResult_Personal_ImportFormat_Staking_Vote_VoteParams_AccountVoteInfo_VoteInfo_VoteList_NodeReq_Name_NameInfo_PeersParams_KeyParams_ServerInfo_ServerInfo_StatusEntry_ServerInfo_ConfigEntry_ConfigItem_ConfigItem_PropsEntry_EventList_ConsensusInfo_EnterpriseConfigKey_EnterpriseConfig)
#endif


/* @@protoc_insertion_point(eof) */
